apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: config-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                # makes k8s wait for 5 seconds before sending the SIGTERM
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8888
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: https://github.com/daviag/bs-config-repo.git